name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Create main tag'
        id: 'main'
        uses: butlerlogic/action-autotag@1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'v'

      - name: 'Create latest tag'
        if: ${{ contains(steps.main.outputs.tagname, 'v') }}
        uses: EndBug/latest-tag@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Create js tag'
        uses: butlerlogic/action-autotag@1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          root: '/packages/embeds/js'
          tag_prefix: 'js-v'

      - name: 'Create react tag'
        uses: butlerlogic/action-autotag@1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          root: '/packages/embeds/react'
          tag_prefix: 'react-v'

      - name: 'Create nextjs tag'
        uses: butlerlogic/action-autotag@1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          root: '/packages/embeds/nextjs'
          tag_prefix: 'nextjs-v'
